### ISSUE TITLE
first oid skipped when doing walk

### ISSUE THREAD

**Issue by amoruck** [Guyverix/snmp-monitoring#1]
Hello, 
First, thank you very much this script is actually very useful, but I think I have found a little issue; 

My oid files: 

$ ls /opt/snmp-monitoring/data/ | grep oid.1.3.6.1.4.1.30911.1
oid.1.3.6.1.4.1.30911.1.101
oid.1.3.6.1.4.1.30911.1.102
oid.1.3.6.1.4.1.30911.1.201
oid.1.3.6.1.4.1.30911.1.301

with content like this: 
$ cat /opt/snmp-monitoring/data/oid.1.3.6.1.4.1.30911.1.101
.1.3.6.1.4.1.30911.1.101
integer
65002

Now, when I do walk from 1.3.6.1.4.1.30911.1 i would expect to see all four items, but instead first one ("101") is skipped. 

$ snmpwalk -v 3 -l authNoPriv -u cpsnmpq -A xxxxxxxxx 10.66.250.117  1.3.6.1.4.1.30911.1
SNMPv2-SMI::enterprises.30911.1.102 = INTEGER: 65003
SNMPv2-SMI::enterprises.30911.1.201 = INTEGER: 65001
SNMPv2-SMI::enterprises.30911.1.301 = INTEGER: 65001

I have tried to run with -x (which is very usefull), and it seems that in case we are starting from "non-leaf" oid, expression:

local nextOid=$(ls ${O_PATH} | grep -A1 ${OID} | head -2 | tail -1 | sed 's/oid//')

will skip first existing file (because it tries to get "next" to requested)

**Comment by amoruck** [comment]
I have fixed this with additional condition (but I'm too noob to submit pull request and not sure if it does not break something else - it works for me at least:)

```
if [[ -e ${O_PATH}/${PREFIX}${OID} ]];then
    # Next in the file system (may NOT be a concurrent number)
    local nextOid=$(ls ${O_PATH} | grep -A1 ${OID} | head -2 | tail -1 | sed 's/oid//')
else
    local nextOid=$(ls ${O_PATH} | grep ${OID} | head -1 | sed 's/oid//')
fi
```

**Comment by Guyverix** [comment]
Grin!  Im glad you caught that!  Thank you.  I will get that cleaned up and updated in the repo.

**Comment by Guyverix** [comment]
Committed, and verified.  contrib file updated as well.
